name: ros2-listener-component
version: '0.1'
summary: Basic ROS2 listener component
description: |
  Basic ROS2 listener component based on core20
grade: stable
confinement: strict
base: core20

parts:
  listener-component:
    plugin: colcon
    source: .
    stage-packages: [ros-foxy-ros2run]

apps:
  ros2:
    command: opt/ros/foxy/bin/ros2
    plugs: [network, network-bind]
    extensions: [ros2-foxy]