name: snapped-ros2-pkg
version: '0.1'
summary: Basic ROS 2 package snap
description: |
  Basic ROS 2 package snap with config and launchfile based on core22
grade: stable
confinement: strict
base: core22

parts:
  snapped-ros2-pkg:
    plugin: colcon
    source: .
    stage-packages: [ros-humble-ros2launch]

apps:
  snapped-ros2-launch:
    command: opt/ros/humble/bin/ros2 launch snapped_ros2_pkg snapped.launch.py
    plugs: [network, network-bind]
    extensions: [ros2-humble]
