name: ros2-humble-talker-listener
version: '0.1'
summary: ROS 2 Humble Talker/Listener Example
description: |
 This example launches a ROS 2 Humble talker and listener.

grade: stable
confinement: strict
base: core22

parts:
 ros-demos:
   plugin: colcon
   source: https://github.com/ros2/demos.git
   source-branch: humble
   source-subdir: demo_nodes_cpp
   stage-packages: [ros-humble-ros2launch]

apps:
 ros2-humble-talker-listener:
   command: opt/ros/humble/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
   plugs: [network, network-bind]
   extensions: [ros2-humble]

