name: ros2-talker-listener
version: '0.1'
summary: ROS2 Talker/Listener Example
description: |
  This example launches a ROS2 talker and listener.

grade: devel
confinement: strict
base: core20

package-repositories:
- components: [main]
  formats: [deb]
  key-id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  key-server: keyserver.ubuntu.com
  suites: [focal]
  type: apt
  url: http://repo.ros2.org/ubuntu/main

parts:
  ros2-galactic-extension:
    build-packages: [ros-galactic-ros-core]
    override-build: install -D -m 0755 launch ${SNAPCRAFT_PART_INSTALL}/snap/command-chain/ros2-launch
    plugin: nil
    source: $SNAPCRAFT_EXTENSIONS_DIR/ros2

  ros-demos:
    after: [ros2-galactic-extension]
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: galactic
    source-subdir: demo_nodes_cpp
    stage-packages: [ros-galactic-ros2launch]
    build-environment:
    - ROS_VERSION: '2'
    - ROS_DISTRO: galactic

apps:
  ros2-talker-listener:
    command: opt/ros/galactic/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
    plugs: [network, network-bind]
    command-chain: [snap/command-chain/ros2-launch]
    environment:
      PYTHONPATH: $SNAP/opt/ros/galactic/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages:${PYTHONPATH}
      ROS_DISTRO: galactic
      ROS_VERSION: '2'
