name: snapped-ros1-pkg # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Basic ROS1 package snap # 79 char long summary
description: |
  Basic ROS1 package snap with config and launchfile based on core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snapped-ros1-pkg:
    # See 'snapcraft plugins'
    plugin: catkin
    source: .
    source-space: snapped_ros1_pkg
    build-packages:
      - lsb-release
    stage:
      # remove link so snapcraft security check doesn't fail
      - -lib/systemd/system/sudo.service

apps:
#  roscore:   # necessary only if you want to start the roscore from this snap
#    command: opt/ros/melodic/bin/roscore
#    plugs: [network, network-bind]
#
  snapped-ros1-pkg:
    command: opt/ros/melodic/bin/rosrun snapped_ros1_pkg snapped_ros1_pkg_node
    plugs: [network, network-bind]

  snapped-ros1-launch:
    command: opt/ros/melodic/bin/roslaunch snapped_ros1_pkg snapped.launch
    plugs: [network, network-bind]
