name: ros2-shared-memory
version: '0.1'
summary: ROS2 shared-memory example
description: |
  This example launches a ROS2 talker and listener with shared-memory

confinement: strict
base: core20

plugs:
  shared-memory:
    private: true

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/ros2/demos.git
    source-branch: foxy
    source-subdir: demo_nodes_cpp
    stage-packages: [ros-foxy-ros2launch]

apps:
  ros2-talker-listener:
    command: opt/ros/foxy/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
    extensions: [ros2-foxy]
    plugs: [network, network-bind]

