name: snapped-ros1-pkg # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Basic ROS1 package snap # 79 char long summary
description: |
  Basic ROS1 package snap with config and launchfile based on core20
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snapped-ros1-pkg:
    # See 'snapcraft plugins'
    plugin: catkin
    source: .
    catkin-packages: [roscpp_tutorials]
    build-packages:
      - git
      - python3-vcstool
    stage-packages:
      - ros-noetic-rosbash # necessary if we need rosrun
      - ros-noetic-roslaunch # necessary if we need roslaunch
    override-pull: |
          snapcraftctl pull # Here we are going to use the local .rosinstall file
          # import ROS 1 package
          vcs import --input snapped_ros1_pkg.rosinstall

          # This demonstrates that the rosinstall file can be retrieve from a URL
          # vcs import --input https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos

apps:
  # launching this application doesn't start the roscore unlike the second app using the launchfile
  talker:
    command: opt/ros/noetic/bin/rosrun roscpp_tutorials talker
    plugs: [network, network-bind]
    extensions: [ros1-noetic]

  snapped-ros1-launch:
    command: opt/ros/noetic/bin/roslaunch roscpp_tutorials talker_listener.launch
    plugs: [network, network-bind]
    extensions: [ros1-noetic]
